version: "3.9"

services:

  movienator-express:
    build:
      context: ./movienator_express
      dockerfile: Dockerfile
    container_name: movienator-express-server
    environment:
        TZ: "Europe/Berlin"
    ports:
      - '8080:8080'
      - '9229:9229'
    volumes:
      - ./movienator_express:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
      - database-test
    networks:
      - movienator_network

  database:
    build:
      context: ./movienator_mysql
      dockerfile: Dockerfile
    container_name: movienator-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movienator-database
      MYSQL_USER: public
      MYSQL_PASSWORD: public
    ports:
        - "3306:3306"
    volumes:
        - dbdata:/var/lib/mysql
    networks:
      - movienator_network

  database-test:
    build:
      context: ./movienator_mysql_test
      dockerfile: Dockerfile
    container_name: movienator-database-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movienator-database-test
      MYSQL_USER: public
      MYSQL_PASSWORD: public
    ports:
      - "3307:3306"
    networks:
      - movienator_network

  phpadmin:
    build:
      context: ./movienator_phpadmin
      dockerfile: Dockerfile
    container_name: movienator-phpadmin
    networks:
      - movienator_network
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306

  react:
    build:
      context: ./movienator_react
      dockerfile: Dockerfile
    container_name: movienator-react
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./movienator_react:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      - CHOCKIDAR_USEPOLLING=true
    depends_on:
      - movienator-express

volumes:
  dbdata:


networks:
  movienator_network:
    name: movienator_net
    driver: bridge
